### ISSUE TITLE
linkDefault no longer works on iOS with Expo SDK 39

### ISSUE THREAD

**Issue by karanmartian** [obipawan/react-native-hyperlink#56] opened 2020-09-29 19:04 UTC
Only on iOS seeing this issue, have to explicitly mention Linking.openURL in onPress func. This is after upgrading to RN Expo 39.0.0 SDK

**Comment by rrufus** [comment] 2020-11-10 10:29
It also appears not to work on iOS14.1 with RN Expo 38.0.0 SDK, but explicitly mentioning Linking.openURL had no effect.

I'm going to try updating to Expo 39.0.0 SDK in the hope that the workaround of using onPress works there.

**Comment by eladcandroid** [comment] 2020-12-03 13:24
Any news?

**Comment by ShaneKeney** [comment] 2020-12-04 19:33
Also have a project that is running RN Expo 39.0.0.  On iOS I am noticing that the onPress seems to not fire.  The onLongPress does fire though.  

A workaround here is to add your own `Linking` logic but I'd rather have a fix for the `onPress` to fire correctly.

**Comment by obipawan** [comment] 2020-12-05 05:58
This is weird. I don't have an iOS device atm, I'm hoping this is reproducible on the simulators?

**Comment by ShaneKeney** [comment] 2020-12-23 18:16
@obipawan Also noticed that this is only occurring for situations where Google Chrome is set as default browser.  When I set my default browser to Safari, it works per usual.

**Comment by koushikmohan1996** [comment] 2021-01-02 13:18
@ShaneKeney I am having the same issue as chrome is set as the default browser. Did you find any solution for this

**Comment by koushikmohan1996** [comment] 2021-01-02 16:40
Never mind it can be fixed by doing this step

https://github.com/obipawan/react-native-hyperlink/issues/57#issuecomment-733001152

**Comment by ShaneKeney** [comment] 2021-01-04 00:05
@koushikmohan1996 We used Expo managed workflow so that solution wouldn't work for us directly.  I'll have to check to see if that is configurable param for Expo app.json config.  Otherwise we may just build out our own.

**Comment by koushikmohan1996** [comment] 2021-01-04 02:57
> @koushikmohan1996 We used Expo managed workflow so that solution wouldn't work for us directly.  I'll have to check to see if that is configurable param for Expo app.json config.  Otherwise we may just build out our own. 

Okay. I was facing many issues like this while using expo. That's the main reason I moved to bare react native. :)

**Comment by ShaneKeney** [comment] 2021-02-03 18:13
This issue seems to be resolved now.  No longer facing these issues.

**Closed** 2022-08-22 15:46 UTC
