### ISSUE TITLE
Dot app domains not linked without http(s)

### ISSUE THREAD

**Issue by robertgaal** [obipawan/react-native-hyperlink#54] opened 2020-08-27 13:58 UTC
**Describe the bug**
A dot app domain (get.app) isn't linked without also adding http or https (https://get.app). This is however true for dot com (github.com / https://github.com) domains and others.

**To Reproduce**
1. Input string "get.app and https://get.app"
2. "get.app" is not linked

**Expected behavior**
2. "get.app" is linked

**Screenshots**
![Screen Shot 2020-08-27 at 15 55 17](https://user-images.githubusercontent.com/5376/91451545-d3c9df80-e87d-11ea-8958-825e0b76bf2f.png)

**Comment by obipawan** [comment] 2020-08-27 15:32
Seems like a duplicate of https://github.com/obipawan/react-native-hyperlink/issues/19#issuecomment-354412306. Give this a shot?

**Comment by robertgaal** [comment] 2020-08-27 16:16
Thanks for the lightning fast response!

I can definitely add a custom handler. But note that when I for instance use .com or .co or .nl, this works as intended. It's just .app where this fails.

Are you saying I should file a bug with linkify-it instead to support the dot app TLD? It appears they use [node-tlds](https://github.com/stephenmathieson/node-tlds) and that does have dot app included.

**Closed** 2022-08-22 15:47 UTC
