### ISSUE TITLE
Doesnt work on my android device

### ISSUE THREAD

**Issue by indrasantosa** [obipawan/react-native-hyperlink#13] opened 2017-05-24 06:35 UTC
Library doest work for android. anyone have the same case?

**Comment by obipawan** [comment] 2017-05-24 07:30
hey @indrasantosa 
Can you provide some more details?

**Comment by indrasantosa** [comment] 2017-05-29 04:59
After I install it and follow thru, the text doesnt changed into a link.
But then when I tested it on ios, I can see it transformed into a link and
works perfectly.

**Comment by obipawan** [comment] 2017-05-29 05:15
can share your component code?

**Comment by obipawan** [comment] 2017-06-20 16:05
ping!

**Comment by obipawan** [comment] 2017-07-09 17:33
Closing this. @indrasantosa please feel free to drop a note with some details if you still feel there's a problem getting this to work on android. 
Also, if the problem is to highlight links, have you tried tinkering with the `linkStyle` prop?

https://github.com/obipawan/react-native-hyperlink#props

**Closed by obipawan** 2017-07-09 17:33 UTC

**Comment by DanielWoldehana** [comment] 2022-02-02 21:24
hey obipawan, I am having similar issues. hyperlink works fine on ios and android simulators but when tested on a real android device the links were there meaning hyperlink did manage to parse the links and apply any linkStyles but when clicked it did not work. code was simply this:
`<Hyperlink linkDefault={true}> 
    <Text> some text and [link here]</Text> 
 </Hyperlink>`
 
 I tried:
 `<Hyperlink 
     linkDefault={true}
     onPress={(url) => Linking.openURL(url)}>
> 
    <Text> some text and [link here]</Text> 
 </Hyperlink>`

that didn't work, but onLongPress={} worked on the real device, which is great but not what I was looking for.

would you happen to have any solutions for this?

**Comment by Parmar-Bansi** [comment] 2024-04-05 05:51
<Hyperlink linkStyle={{ textDecorationLine: 'underline' }} linkDefault={true} >
          <Text style={[styles.conversationText, { color: theme.cardHeadlineTextColor }]}>
          https://reactnative.dev/
          </Text>
      </Hyperlink>
      
      my code not clickable any idea ??
